import { Router, type IRouter } from "express";
import healthRouter from "./health";
import chatRouter from "./chat";
import chatHistoryRouter from "./chat-history";
import kitchenChatRouter from "./kitchen-chat";
import transcribeRouter from "./transcribe";
import restaurantsRouter from "./restaurants";
import ordersRouter from "./orders";
import tablesRouter from "./tables";
import settingsRouter from "./settings";
import feedbackRouter from "./feedback";
import dashboardRouter from "./dashboard";
import visionRouter from "./vision";
import stockRouter from "./stock";
import rentabilidadeRouter from "./rentabilidade";
import employeesRouter from "./employees";
import auditRouter from "./audit";
import cashierSessionRouter from "./cashier-session";
import backupRouter from "./backup";
import lgpdRouter from "./lgpd";
import orderHistoryRouter from "./order-history";
import complaintsRouter from "./complaints";
import onboardingRouter from "./onboarding";
import analyticsRouter from "./analytics";
// REMOVIDO EM 29/07/2026: miar-compat.ts não tinha autenticação nenhuma —
// qualquer pessoa sem login conseguia ler/editar dados de qualquer restaurante
// via URLs tipo /establishments/1/products. Nenhum app atual depende dele.
// import miarCompatRouter from "./miar-compat";
import waiterCallsRouter from "./waiter-calls";
import authRouter from "./auth";
import otpRouter from "./otp";
import clientAuthRouter from "./client-auth";
import passkeysRouter from "./passkeys";
import deliveryObservationsRouter from "./delivery-observations";
import deliveryGovernanceRouter from "./delivery-governance";
import operationalWorkflowRouter from "./operational-workflow";
import segmentPresetsRouter from "./segment-presets";
import barcodeRouter from "./barcode";
import marketingRouter from "./marketing";
import foodAnalysisRouter from "./food-analysis";
import setupRouter from "./setup";
import deliveryInviteRouter from "./delivery-invite";
import registroProtegidoRouter from "./registro-protegido";
import gestoresRouter from "./gestores";
import pixRouter from "./pix";
import demandaRouter from "./demanda";
import comprasRouter from "./compras";
import fornecedoresRouter from "./fornecedores";
import recadosRouter from "./recados";
import miaRouter from "./mia";
import aiKeysRouter from "./ai-keys";
import loyaltyRouter from "./loyalty";
import miarIntelligenceRouter from "./miar-intelligence";
import networkRouter from "./network";
import atalhosRouter from "./atalhos";
import muralEmpregosRouter from "./mural-empregos";
import miarApoiaRouter from "./miar-apoia";
import menuIaRouter from "./menu-ia";
import fiadoRouter from "./fiado";
import financialLedgerRouter from "./financial-ledger";
import driveThruRouter from "./drive-thru";
import lojasRouter from "./lojas";
import loyaltyResgatesRouter from "./loyalty-resgates";
import { aiLimiter } from "../lib/rate-limiter";
import { employees } from "../lib/data-store";
import { requireAnyAuth } from "./auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(otpRouter);
router.use(clientAuthRouter);
router.use(passkeysRouter);
router.use(aiLimiter, chatRouter);
router.use(aiLimiter, chatHistoryRouter);
router.use(aiLimiter, kitchenChatRouter);
router.use(aiLimiter, transcribeRouter);
router.use(restaurantsRouter);
router.use(ordersRouter);
router.use(tablesRouter);
router.use(settingsRouter);
router.use(feedbackRouter);
router.use(dashboardRouter);
router.use(visionRouter);
router.use(stockRouter);
router.use(rentabilidadeRouter);
router.use(employeesRouter);
router.use(setupRouter);
router.use(deliveryInviteRouter);
router.use(registroProtegidoRouter);
router.use(gestoresRouter);
router.use(auditRouter);
router.use(cashierSessionRouter);
router.use(backupRouter);
router.use(lgpdRouter);
router.use(orderHistoryRouter);
router.use(complaintsRouter);
router.use(onboardingRouter);
router.use(analyticsRouter);
router.use(waiterCallsRouter);
// router.use(miarCompatRouter); — DESLIGADO EM 29/07/2026 (sem autenticação, ver comentário no import acima)
router.use(deliveryObservationsRouter);
router.use(deliveryGovernanceRouter);
router.use(operationalWorkflowRouter);
router.use(segmentPresetsRouter);
router.use(barcodeRouter);
router.use(aiLimiter, marketingRouter);
router.use(aiLimiter, foodAnalysisRouter);
router.use(pixRouter);
router.use(demandaRouter);
router.use(comprasRouter);
router.use(fornecedoresRouter);
router.use(recadosRouter);
router.use(aiLimiter, miarIntelligenceRouter);
router.use(aiLimiter, miaRouter);
router.use(aiKeysRouter);
router.use(networkRouter);
router.use(loyaltyRouter);
router.use(atalhosRouter);
router.use(muralEmpregosRouter);
router.use(miarApoiaRouter);
router.use(menuIaRouter);
router.use(fiadoRouter);
router.use(financialLedgerRouter);
router.use(loyaltyResgatesRouter);
router.use(driveThruRouter);
router.use(lojasRouter);

router.get("/features/miar-edita", requireAnyAuth, (req, res): void => {
	const auth = (req as any).auth as { role?: string; isEmployee?: boolean; employeeId?: string };
	const employee = auth.isEmployee && auth.employeeId
		? employees.find((item) => item.id === auth.employeeId)
		: null;
	res.json({ enabled: auth.role === "owner" || Boolean(employee?.permissions.useMiarEdita) });
});

export default router;
